#!/usr/bin/env node
/* Bundle every data/*.json file into assets/db.js as `window.DB`.
 *
 * Node twin of build.py — identical output, for machines without Python.
 * Browsers block fetch() of local files over file://, so this inlines the
 * canonical dummy dataset into one JS bundle the prototype loads by just
 * double-clicking index.html — no local server required.
 *
 * Re-run after editing any data file:   node build.js
 */
const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const DATA = path.join(ROOT, 'data');
const OUT = path.join(ROOT, 'assets', 'db.js');

// filename (without .json) -> key on window.DB
const db = {};
fs.readdirSync(DATA)
  .filter((f) => f.endsWith('.json'))
  .sort()
  .forEach((f) => {
    const key = path.basename(f, '.json');
    db[key] = JSON.parse(fs.readFileSync(path.join(DATA, f), 'utf8'));
  });

fs.mkdirSync(path.dirname(OUT), { recursive: true });
const header =
  '// AUTO-GENERATED by build.js from data/*.json — do not edit by hand.\n' +
  '// Canonical source of truth is the JSON files under prototype/data/.\n' +
  `// Generated ${new Date().toISOString().slice(0, 19)}\n`;
fs.writeFileSync(OUT, header + 'window.DB = ' + JSON.stringify(db, null, 2) + ';\n');

const counts = {};
Object.keys(db).forEach((k) => { counts[k] = Array.isArray(db[k]) ? db[k].length : 1; });
console.log('bundled ->', OUT);
console.log('keys:', counts);
