#!/usr/bin/env python3
"""Bundle every data/*.json file into assets/db.js as `window.DB`.

The JSON files under data/ are the canonical dummy dataset (they match the
requirement data model). Browsers block fetch() of local files over file://,
so this build inlines them into a single JS bundle the prototype can load by
just double-clicking index.html — no local server required.

Re-run after editing any data file:   python3 build.py
"""
import json, os, glob, datetime

ROOT = os.path.dirname(os.path.abspath(__file__))
DATA = os.path.join(ROOT, "data")
OUT = os.path.join(ROOT, "assets", "db.js")

# filename (without .json) -> key on window.DB
db = {}
for path in sorted(glob.glob(os.path.join(DATA, "*.json"))):
    key = os.path.splitext(os.path.basename(path))[0]
    with open(path, encoding="utf-8") as f:
        db[key] = json.load(f)

os.makedirs(os.path.dirname(OUT), exist_ok=True)
header = (
    "// AUTO-GENERATED by build.py from data/*.json — do not edit by hand.\n"
    "// Canonical source of truth is the JSON files under prototype/data/.\n"
    f"// Generated {datetime.datetime.now().isoformat(timespec='seconds')}\n"
)
with open(OUT, "w", encoding="utf-8") as f:
    f.write(header)
    f.write("window.DB = ")
    json.dump(db, f, indent=2)
    f.write(";\n")

counts = {k: (len(v) if isinstance(v, list) else 1) for k, v in db.items()}
print("bundled ->", OUT)
print("keys:", counts)
